---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: penning

spec:
  refreshInterval: 1h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /shazean/penning/credentials
