---
apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: penning

spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: penning
    spec:
      containers:
        - name: app
          image: ghcr.io/shazean/penning:latest
          envFrom:
            - configMapRef:
                name: penning
            - configMapRef:
                name: penning-env
            - secretRef:
                name: credentials
          env: []
          resources:
            requests:
              cpu: "20m"
              memory: "55M"
      restartPolicy: Always
      imagePullPolicy: Always
